apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: demo-alerts
  namespace: monitoring
  labels:
    release: kps
spec:
  groups:
  - name: demo.alerts
    rules:
    # 1) Pod not ready (generic)
    - alert: KubePodNotReady
      expr: |
        sum by (namespace, pod) (kube_pod_status_ready{condition="true"} == 0)
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Pod not ready ({{ $labels.namespace }}/{{ $labels.pod }})"
        description: "Pod has been not ready for >2m."

    # 2) High CPU for demo namespace (5m avg)
    - alert: HighCPUUtilizationDemo
      expr: |
        sum by (namespace) (
          rate(container_cpu_usage_seconds_total{namespace="demo",container!="",image!=""}[5m])
        ) > 0.2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU in namespace demo"
        description: "CPU > 0.2 cores for 5m in namespace demo."